import Link from 'next/link'
import { Metadata } from 'next'
import { PlusIcon } from 'lucide-react'
import { ROUTES } from '@/consts/routes'
import { buttonVariants } from '@/components/ui/button'
import { adminGetCourses } from '@/app/data/admin/admin-get-courses'
import AdminCourseList from '@/app/(admin)/dashboard/courses/_components/AdminCourseList'
import AdminCourseEmpty from '@/app/(admin)/dashboard/courses/_components/AdminCourseEmpty'
import { Suspense } from 'react'
import AdminCourseSkeletonLayout from '@/app/(admin)/dashboard/courses/_components/AdminCourseSkeletonLayout'

export const metadata: Metadata = {
    title: 'Admin courses - Danh sách khoá học admin',
    description: 'Generated by create next app',
}

export default function CoursesPage() {
    return (
        <>
            <div className='flex items-center justify-between'>
                <h1 className='text-2xl font-bold capitalize'>Your courses</h1>
                <Link
                    href={ROUTES.DASHBOARD_COURSES_CREATE}
                    className={buttonVariants()}
                >
                    <PlusIcon /> New Course
                </Link>
            </div>
            <Suspense fallback={<AdminCourseSkeletonLayout />}>
                <RenderCourses />
            </Suspense>
        </>
    )
}

async function RenderCourses() {
    const data = await adminGetCourses()

    return <>{data?.length === 0 ? <AdminCourseEmpty /> : <AdminCourseList data={data} />}</>
}
