import Link from 'next/link'
import { buttonVariants } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ROUTES } from '@/consts/routes'
import { ArrowLeftIcon, ShieldXIcon } from 'lucide-react'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Forbidden',
    description: 'Generated by create next app',
}

export default function ForbiddenPage() {
    return (
        <main className='flex min-h-screen flex-col items-center justify-center'>
            <Card className='w-full max-w-md'>
                <CardHeader className='text-center'>
                    <div className='text-destructive/10 mx-auto w-fit rounded-full p-4'>
                        <ShieldXIcon className='text-destructive size-16' />
                    </div>

                    <CardTitle className='text-2xl'>Forbidden</CardTitle>
                    <CardDescription className='mx-auto max-w-xs'>
                        Hey! Your are not an admin, which means you cannot create any courses or stuff like that...
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Link
                        href={ROUTES.HOME}
                        className={buttonVariants({ className: 'w-full' })}
                    >
                        <ArrowLeftIcon className='mr-1 size-4' /> Back to home
                    </Link>
                </CardContent>
            </Card>
        </main>
    )
}
