import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Trang chủ',
    description: 'Generated by create next app',
}

export default function Home() {
    return <div>Home page</div>
}
