import HeroSection from '@/app/(public)/_components/HeroSection'
import FeaturesSection from '@/app/(public)/_components/FeaturesSection'

import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Trang chủ',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <main className='relative min-h-screen space-y-20 pt-20'>
            <HeroSection />
            <FeaturesSection />
        </main>
    )
}
